FROM node:alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY ["package.json", "."]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
CMD npm run test
CMD npm start